LCManagerClient/LCManager.Site/Controllers/GoodController.cs
namespace LC_Manager.Controllers
{
    using System.Collections.Generic;
    using Implementation.Data;
    using OfficeOpenXml;
    using Implementation;
    using Implementation.RequestData;
    using Implementation.ResponseData;
    using Models;
    using Newtonsoft.Json;
    using System;
    using System.Linq;
    using System.Net.Http;
    using System.Web;
    using System.Web.Mvc;

    public class GoodController : Controller
    {
        [AuthorizeJwt(Roles = "Goods")]
        public ActionResult Index()
        {
            try
            {
                ViewBag.OperatorName = Convert.ToString(HttpContext.Request.Cookies["operatorName"].Value);
                ViewBag.RoleName = JwtProps.GetRole();
            }
            catch { }
            return View();
        }

        [AuthorizeJwt(Roles = "GoodsMyGoods")]
        public string GetGoods()
        {
            OperatorGoodsResponse operatorGoodsResponse = new OperatorGoodsResponse();
            try
            {
                OperatorGoodsRequest operatorGoodsRequest = new OperatorGoodsRequest
                {
                    Operator = JwtProps.GetOperator()
                };
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/values/OperatorGoods", operatorGoodsRequest).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    operatorGoodsResponse = responseMessage.Content.ReadAsAsync<OperatorGoodsResponse>().Result;
                    if (operatorGoodsResponse.ErrorCode == 0 && string.IsNullOrEmpty(operatorGoodsResponse.Message))
                    {
                        goodsdata data = new goodsdata();
                        foreach (var c in operatorGoodsResponse.OperatorGoods)
                        {
                            good g = new good
                            {
                                chek = "<input type='checkbox' class='checkbox checkbox-for-good' name='checkbox[]" + c.Id + "' id='checkbox" + c.Id + "' value='" + c.Id + "'><label for='checkbox" + c.Id + "'></label>",
                                id = c.Id.ToString(),
                                name = c.Code,
                                text = c.Name
                            };
                            data.data.Add(g);
                        }
                        return JsonConvert.SerializeObject(data);
                    }
                    return JsonConvert.SerializeObject(operatorGoodsResponse);
                }
                else
                {
                    operatorGoodsResponse.ErrorCode = 10;
                    operatorGoodsResponse.Message = "Ошибка получения данных";
                }
            }
            catch (Exception ex)
            {
                operatorGoodsResponse.ErrorCode = 2;
                operatorGoodsResponse.Message = ex.Message;
            }
            return JsonConvert.SerializeObject(operatorGoodsResponse);
        }

        //Сохранение списка товаров через Ajax
        [AuthorizeJwt(Roles = "GoodsMyGoodsList")]
        public string OperatorGoodListSave(string list_name, string list_id)
        {
            var operatorGoodListResponse = new OperatorGoodListResponse();
            try
            {
                var data = new OperatorGoodListCreateRequest
                {
                    Operator = JwtProps.GetOperator(),
                    GoodList = list_id.Split(',').Select(n => Convert.ToInt32(n)).ToList(),
                    GoodListName = list_name
                };
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/values/SaveOperatorGoodList", data).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    operatorGoodListResponse = responseMessage.Content.ReadAsAsync<OperatorGoodListResponse>().Result;
                    if (operatorGoodListResponse.ErrorCode == 0 && string.IsNullOrEmpty(operatorGoodListResponse.Message))
                    {
                        return JsonConvert.SerializeObject(new { success = true });
                    }
                    return JsonConvert.SerializeObject(operatorGoodListResponse);
                }
                operatorGoodListResponse.ErrorCode = 10;
                operatorGoodListResponse.Message = "Ошибка получения данных";
            }
            catch (Exception ex)
            {
                operatorGoodListResponse.ErrorCode = 2;
                operatorGoodListResponse.Message = ex.Message;
            }
            return JsonConvert.SerializeObject(operatorGoodListResponse);
        }

        //Подгузка списка списков товаров через Ajax для Jquery DataTable
        [AuthorizeJwt(Roles = "GoodsMyGoodsList")]
        public string OpretorGoodListGet()
        {
            OperatorGoodListResponse operatorGoodResponse = new OperatorGoodListResponse();
            try
            {
                OperatorGoodsRequest operatorGoodRequest = new OperatorGoodsRequest
                {
                    Operator = JwtProps.GetOperator()
                };
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/values/OperatorGoodList", operatorGoodRequest).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    operatorGoodResponse = responseMessage.Content.ReadAsAsync<OperatorGoodListResponse>().Result;
                    if (operatorGoodResponse.ErrorCode == 0 && string.IsNullOrEmpty(operatorGoodResponse.Message))
                    {
                        GoodModel.GoodListData data = new GoodModel.GoodListData();
                        foreach (var c in operatorGoodResponse.GoodLists)
                        {
                            #region Формируем выпадающий список для списка ТТ
                            var detailList = c.Goods.Aggregate(string.Empty, (current, good) => current + (@"<tr>
                                        <td colspan='2' style='color:#000;'>" + good.Code + @"</td>
                                        <td colspan='2' style='color:#000;'>" + good.Name+ @"</td>
                                      </tr>"));
                            #endregion
                            Implementation.Data.OperatorGoodList g = new Implementation.Data.OperatorGoodList
                            {
                                Id = c.Id,
                                Name = c.Name,
                                Text = c.Goods.Count().ToString(),
                                Goods = c.Goods,
                                HtmlForDelete = "<img class='dell-control' data-id=" + c.Id + " src='/img/dell.png'>",
                                details = detailList
                            };
                            data.data.Add(g);
                        }
                        return JsonConvert.SerializeObject(data);
                    }
                    return JsonConvert.SerializeObject(operatorGoodResponse);
                }
                operatorGoodResponse.ErrorCode = 10;
                operatorGoodResponse.Message = "Ошибка получения данных";
            }
            catch (Exception ex)
            {
                operatorGoodResponse.ErrorCode = 2;
                operatorGoodResponse.Message = ex.Message;
            }
            return JsonConvert.SerializeObject(operatorGoodResponse);
        }

        //Удаление списка товаров через Ajax
        [AuthorizeJwt(Roles = "GoodsMyGoodsList")]
        public JsonResult OperatorGoodListRemove(Int16 id)
        {
            DefaultResponse defaultResponse = new DefaultResponse();
            try
            {
                OperatorGoodRemoveRequest operatorGoodRemoveRequest = new OperatorGoodRemoveRequest
                {
                    OperatorGoodList = id
                };
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/values/RemoveOperatorGoodList", operatorGoodRemoveRequest).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    defaultResponse = responseMessage.Content.ReadAsAsync<DefaultResponse>().Result;
                    if (defaultResponse.ErrorCode == 0 && string.IsNullOrEmpty(defaultResponse.Message))
                    {
                        return Json(new { success = true });
                    }
                    return Json(new { success = false, error = JsonConvert.SerializeObject(defaultResponse) });
                }
                defaultResponse.ErrorCode = 10;
                defaultResponse.Message = "Ошибка удаления данных";
            }
            catch (Exception ex)
            {
                defaultResponse.ErrorCode = 10;
                defaultResponse.Message = ex.Message;
            }
            return Json(new { success = false, error = JsonConvert.SerializeObject(defaultResponse) });
        }

        [HttpPost]
        [AuthorizeJwt(Roles = "GoodsMyGoodsList")]
        public JsonResult OperatorGoodImportFromExcel(HttpPostedFileBase file)
        {
            if (Request.Files.Count > 0)
            {
                var goodList = new List<Good>();
                using (var excel = new ExcelPackage(Request.Files[0].InputStream))
                {
                    var sheet = excel.Workbook.Worksheets.First();
                    for (var rowNum = 2; rowNum <= sheet.Dimension.End.Row; rowNum++)
                    {
                        try
                        {
                            goodList.Add(new Good
                            {
                                Code = sheet.Cells[rowNum, 2].Text,
                                Name = sheet.Cells[rowNum, 1].Text
                            });
                        }
                        catch { }
                    }
                }

LCManagerClient/LCManager.Site/Views/Good/Index.cshtml
@{
    ViewBag.Title = "ShopsGoods";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section ContentHeaderNav
{
    @if (ViewBag.RoleName.Contains("OperatorBonusAdd"))
    {
        <li><a href="" id="HandBonusAdd"><img src="../img/plus.png" alt="addbonus"><span>Начислить бонусы</span></a></li>
    }
    @if (ViewBag.RoleName.Contains("OperatorBonusRedeem"))
    {
        <li><a href="" id="HandBonusRedeem"><img src="../img/minus.png" alt="message"><span>Списать бонусы</span></a></li>
    }
    @if (!ViewBag.RoleName.Contains("OperatorBonusAdd") && !ViewBag.RoleName.Contains("OperatorBonusRedeem"))
    {
        <li><a style="visibility:hidden;">.</a></li>
    }
    @if (ViewBag.RoleName.Contains("ActivateCard"))
    {
        <li><a href="#" id="activateCard"><img src="../img/plus.png" alt="addclient"><span>Активировать карту</span></a></li>
    }
    @*<li><a href="@(Url.Action("Clients", "Home"))"><img src="../img/plus.png" alt="addclient"><span>Добавить клиентов</span></a></li>*@
    @*<li><a href=""><img src="~/img/icon-top-menu/help.png" alt="help"><span>Помощь</span></a></li>*@
}

@section ContentHeader
{
    <div class="client_nav">
        @if (ViewBag.RoleName.Contains("GoodsMyGoods"))
        {
            <div><div>?<p>В данном разделе Вы найдете подборку кратких инструкций по использованию данного интерфейса и обслуживанию участников Программы лояльности.</p></div><a href="#my_itte" class="this-p">Товары</a></div>
        }
        @if (ViewBag.RoleName.Contains("GoodsMyGoodsList"))
        {
            <div><div>?<p>Мои списки товаров</p></div><a href="#my_list_itte">Мои списки товаров</a></div>
        }
        <div class="shopvievshop"><p>Всего товаров: <span class="goodshopTablecont">0</span></p></div>
    </div>
}

@section Scripts
{
    <script type="text/javascript">
        function Action() {
            var checked = [];
            $(".checkbox-for-good:checked").each(function ()
            {
                checked.push(parseInt($(this).val()));
            });
            $("#selected_goods").val(checked.join(","));

            var name = $("#good_list_name").val();
            if (name === '') {
                DialogError("Ошибка", "Укажите наименование списка");
                return;
            }

            var selected_goods = $("#selected_goods").val();
            if (selected_goods === '') {
                DialogError("Ошибка", "Нужно выбрать хотя бы 1 товар");
                return;
            }

            $.ajax({
                url: "@Url.Action("OperatorGoodListSave", "Good")",
                type: "POST",
                data: { 'list_name': name, 'list_id': selected_goods},
                success: function (response) {
                    const data = JSON.parse(response);
                    if (data.success === true) {
                        DialogSuccess("Список добавлен!");
                    }
                    else {
                        DialogError("Ошибка", response);
                        console.log(response);
                    }
                },
                error: function (response) {
                    DialogError("Ошибка", response);
                    console.log(response);
                }
            });
        }

        $(document).on('click',
            '.dell-control',
            function() {
                var id = $(this).data('id');
                ConfirmDialog('Подтверждаете удаление?').then(function(resolve) {
                    if (resolve) {
                        $.ajax({
                            url: "@Url.Action("OperatorGoodListRemove", "Good")",
                            type: "POST",
                            data: { 'id': id },
                            success: function(response) {
                                if (response.success === true) {
                                    DialogSuccess("Список удалён!");
                                } else {
                                    DialogError("Ошибка", response);
                                    console.log(response);
                                }
                            },
                            error: function(response) {
                                DialogError("Ошибка", response);
                                console.log(response);
                            }
                        });
                    }
                }).catch(function(reject) {
                    console.log(reject);
                });
            });

        $(function () {
            $("#checkbox0").on('change',
                function () {
                    var selected_goods = $('.checkbox-for-good:checked').length;
                    $("#count_of_goods").html(selected_goods + " тов.");
                });

            $("#goodshopTable").on('change',
                '.checkbox-for-good',
                function () {
                    var selected_goods = $('.checkbox-for-good:checked').length;
                    $("#count_of_goods").html(selected_goods + " тов.");
                });

            $("#add_good_submit").on("click",
                function () {
                    ConfirmDialog('Подтверждаете добавление?').then(function (resolve) {
                        if (resolve) {
                            Action();
                        }
                    }).catch(function (reject) {
                        console.log(reject);
                    });
                });

            $('#goodshopTable').DataTable({
                "processing": true,
                "language": {
                    processing: '<div class="wrapper-for-loading-datatable"><img src="/img/loading-element-1.svg" alt="Alternate Text" /><span class="sr-only">Загрузка...</span></div>'
                },
                "ajax": "@Url.Action("GetGoods", "Good")",
                "columns": [
                    { "data": "chek" },
                    { "data": "name" },
                    { "data": "text" }
                ],
                "ordering": false,
                initComplete: function () {
                    console.log(this);
                    $("#shopsTable_length").appendTo($(".client_nav"));
                    $("#shopsTable_length").css('display', 'flex');
                    $("#shopsTable_length").addClass('shopvievbuttom');
                    $(".goodshopTablecont").html(this.api().data().count());
                    this.api().columns([1, 2]).every(function () {
                        addInputFilter(this);
                    });
                    niceSelect();
                }
            });

            var goodshopTablelist = $('#goodshopTablelist').DataTable({
                "ajax": "@Url.Action("OpretorGoodListGet", "Good")",
                "columns": [
                    {
                        "className": 'details-control',
                        "orderable": false,
                        "data": null,
                        "defaultContent": '<img src="/img/tableiconopen.png">'
                    },
                    { "data": "Name" },
                    { "data": "Text" },
                    {
                        "orderable": false,
                        "data": "HtmlForDelete"
                    }
                ],
                "ordering": false,
                "lengthChange": false,
                initComplete: function () {
                    this.api().columns([1, 2]).every(function () {
                        addInputFilter(this);
                    });
                }
            });

            $('#goodshopTablelist tbody').on('click', 'tr.odd td:nth-child(1), tr.odd td:nth-child(2), tr.odd td:nth-child(3), tr.even td:nth-child(1), tr.even td:nth-child(2), tr.even td:nth-child(3)', function () {
                var tr = $(this).closest('tr');
                var row = goodshopTablelist.row(tr);
                showHideRow(tr, row, shopTablelistData);
            });

            function shopTablelistData(d) {
                return '<tbody>' + d.details + '</tbody>';
            }

            $("#upload-goods-from-file").click(function(e) {
                e.preventDefault();
                $("#file-goods").click();
            });

            $("#file-goods").change(function () {
                ConfirmDialog('Подтверждете добавление?').then(function (resolve) {
                    if (resolve) {
                        var fileUpload = $("#file-goods").get(0);
                        var files = fileUpload.files;
                        var fileData = new FormData();
                        for (var i = 0; i < files.length; i++) {
                            fileData.append(files[i].name, files[i]);
                        };

                        $.ajax({
                            url: "@Url.Action("OperatorGoodImportFromExcel","Good")",
                            type: "POST",
                            data: fileData,
                            cache: false,
                            contentType: false,
                            processData: false,
                            success: function (response) {
                                if (response.success === true) {
                                    DialogSuccess("УСПЕШНО!");
                                } else {
                                    DialogError("Ошибка", response);
                                    console.log(response);
                                }
                            },
                            error: function (response) {
                                DialogError("Ошибка", response);
                                console.log(response);
                            }
                        });
                    }
                });
            });
        });
    </script>
}

<section class="table-min-width">
    <div class="my_action_waper goodshop">
        <div class="form-terminal__tabs-content">
            @if (ViewBag.RoleName.Contains("GoodsMyGoods"))
            {
                <div id="my_itte" class="@(ViewBag.RoleName.Contains("GoodsMyGoods") ? "active" : "")">
                    <div class="addclientlist-left">
                        <table id="goodshopTable" class="display clientlist" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th><div>?<p>123</p></div><input type='checkbox' class='checkbox' name='checkbox1' id='checkbox0'><label for='checkbox0'></label></th>
                                    <th><p>Артикул</p></th>
                                    <th><p>Наименование товара</p></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <div class="godshopright">
                        <div class="godshop_add_header">
                            <a href="" id="upload-goods-from-file">Загрузить товары</a>
                            <input type="file" class="hidden" name="file-goods" id="file-goods" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
                            <a href="@Url.Action("OperatorGoodDownloadTemplate","Good")">Скачать образец</a>
                        </div>
                        <div class="godshop_add_cont">
                            <a class="active">Создать список для акции</a>
                            <input type="text" id="good_list_name" placeholder="Введите наименование списка">
                            <input type="text" name="selected_goods" class="addshopinput" style="display: none !important" id="selected_goods">
                            <div class="godshop_add_cont_count" id="count_of_goods">0 тов.</div>
                            <button id="add_good_submit" disabled>Сохранить в мои списки</button>
                            <div>?<p>123123213</p></div>
                        </div>
                    </div>
                </div>
            }
            @if (ViewBag.RoleName.Contains("GoodsMyGoodsList"))
            {
                <div id="my_list_itte" class="@(ViewBag.RoleName.Contains("GoodsMyGoodsList") && !ViewBag.RoleName.Contains("GoodsMyGoods") ? "active" : "")">
                    <table id="goodshopTablelist" class="display clientlist" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th></th>
                                <th><p>Наименование списка</p></th>
                                <th><p>Кол-во SKU</p></th>
                                <th></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            }
        </div>
    </div>
</section>