LCManagerClient/LCManager.Site/Controllers/PosController.cs
namespace LC_Manager.Controllers
{
    using System;
    using System.Web.Mvc;
    using Implementation;
    using System.Linq;
    using System.Net.Http;
    using Implementation.RequestData;
    using Implementation.ResponseData;
    using Models;
    using Newtonsoft.Json;

    public class PosController : Controller
    {
        // GET: Shop
        [AuthorizeJwt(Roles = "Shops")]
        public ActionResult Index()
        {
            try
            {
                ViewBag.OperatorName = Convert.ToString(HttpContext.Request.Cookies["operatorName"].Value);
                ViewBag.RoleName = JwtProps.GetRole();
            }
            catch { }
            return View();
        }

        ///// <summary>
        ///// Получает модель для представления, содержащая сразу и список магазинов и списки оператора
        ///// </summary>
        ///// <returns></returns>
        //private PosModel.PosViewModel GetOperatorPosModel()
        //{
        //    var model = new PosModel.PosViewModel();

        //    OperatorPosResponse operatorPosResponse = new OperatorPosResponse();
        //    try
        //    {
        //        OperatorPosRequest operatorPosRequest = new OperatorPosRequest
        //        {
        //            Operator = JwtProps.GetOperator()
        //        };
        //        HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/pos/OperatorPos", operatorPosRequest).Result;
        //        if (responseMessage.IsSuccessStatusCode)
        //        {
        //            operatorPosResponse = responseMessage.Content.ReadAsAsync<OperatorPosResponse>().Result;
        //            if (operatorPosResponse.ErrorCode == 0 && string.IsNullOrEmpty(operatorPosResponse.Message))
        //            {
        //                //model.Poses = operatorPosResponse.Poses;
        //                //model.OperatorPosLists = operatorPosResponse.PosLists;
        //            }
        //        }
        //        else
        //        {
        //            operatorPosResponse.ErrorCode = 10;
        //            operatorPosResponse.Message = "Ошибка получения данных";
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        operatorPosResponse.ErrorCode = 10;
        //        operatorPosResponse.Message = ex.Message;
        //    }
        //    return model;
        //}

        //Удаление списка ТТ через Ajax
        [AuthorizeJwt(Roles = "ShopsCreateShopList")]
        public JsonResult OperatorPosListRemove(Int16 id)
        {
            DefaultResponse defaultResponse = new DefaultResponse();
            try
            {
                OperatorPosRemoveRequest operatorPosRemoveRequest = new OperatorPosRemoveRequest
                {
                    OperatorPosList = id
                };
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/pos/RemoveOperatorPosList", operatorPosRemoveRequest).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    defaultResponse = responseMessage.Content.ReadAsAsync<DefaultResponse>().Result;
                    if (defaultResponse.ErrorCode == 0 && string.IsNullOrEmpty(defaultResponse.Message))
                    {
                        return Json(new { success = true });
                    }
                    return Json(new { success = false, error = JsonConvert.SerializeObject(defaultResponse) });
                }
                defaultResponse.ErrorCode = 10;
                defaultResponse.Message = "Ошибка удаления данных";
            }
            catch (Exception ex)
            {
                defaultResponse.ErrorCode = 10;
                defaultResponse.Message = ex.Message;
            }
            return Json(new { success = false, error = JsonConvert.SerializeObject(defaultResponse) });
        }

        //Сохранение списка ТТ через Ajax
        [AuthorizeJwt(Roles = "ShopsCreateShopList")]
        public string OperatorPosListSave(string list_name, string list_id)
        {
            var operatorPosListResponse = new OperatorPosListResponse();
            try
            {
                var data = new OperatorPosListCreateRequest
                {
                    Operator = JwtProps.GetOperator(),
                    PosList = list_id.Split(',').Select(n => Convert.ToInt32(n)).ToList(),
                    PosListName = list_name
                };
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/pos/SaveOperatorPosList", data).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    operatorPosListResponse = responseMessage.Content.ReadAsAsync<OperatorPosListResponse>().Result;
                    if (operatorPosListResponse.ErrorCode == 0 && string.IsNullOrEmpty(operatorPosListResponse.Message))
                    {
                        return JsonConvert.SerializeObject(new { success = true });
                    }
                    return JsonConvert.SerializeObject(operatorPosListResponse);
                }
                operatorPosListResponse.ErrorCode = 10;
                operatorPosListResponse.Message = "Ошибка получения данных";
            }
            catch (Exception ex)
            {
                operatorPosListResponse.ErrorCode = 2;
                operatorPosListResponse.Message = ex.Message;
            }
            return JsonConvert.SerializeObject(operatorPosListResponse);
        }

        //Подгузка ТТ через Ajax для Jquery DataTable
        [AuthorizeJwt(Roles = "ShopsMyShops")]
        public string GetOperatorPos()
        {
            OperatorPosResponse operatorPosResponse = new OperatorPosResponse();
            try
            {
                OperatorPosRequest operatorPosRequest = new OperatorPosRequest
                {
                    Operator = JwtProps.GetOperator()
                };
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/pos/OperatorPos", operatorPosRequest).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    operatorPosResponse = responseMessage.Content.ReadAsAsync<OperatorPosResponse>().Result;
                    if (operatorPosResponse.ErrorCode == 0 && string.IsNullOrEmpty(operatorPosResponse.Message))
                    {
                        PosModel.PosData data = new PosModel.PosData();
                        int i = 0;
                        foreach (var c in operatorPosResponse.Poses)
                        {
                            i++;
                            var item = new LC_Manager.Implementation.Data.Pos
                            {
                                Check = "<input type='checkbox' class='checkbox checkbox-for-shop' name='checkbox[]" + c.Id + "' id='checkbox" + c.Id + "' value='" + c.Id + "'><label for='checkbox" + c.Id + "'></label>",
                                Id = c.Id,
                                Address = c.Address,
                                City = c.City,
                                Region = c.Region
                            };
                            data.data.Add(item);
                        }
                        return JsonConvert.SerializeObject(data);
                    }
                    return JsonConvert.SerializeObject(operatorPosResponse);
                }
                else
                {
                    operatorPosResponse.ErrorCode = 10;
                    operatorPosResponse.Message = "Ошибка получения данных";
                }
            }
            catch (Exception ex)
            {
                operatorPosResponse.ErrorCode = 2;
                operatorPosResponse.Message = ex.Message;
            }
            return JsonConvert.SerializeObject(operatorPosResponse);
        }

        //Подгузка списка списков ТТ через Ajax для Jquery DataTable
        [AuthorizeJwt(Roles = "ShopsCreateShopList")]
        public string GetListOfPos()
        {
            OperatorPosListResponse operatorPosResponse = new OperatorPosListResponse();
            try
            {
                OperatorPosRequest operatorPosRequest = new OperatorPosRequest
                {
                    Operator = JwtProps.GetOperator()
                };
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/pos/OperatorPosList", operatorPosRequest).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    operatorPosResponse = responseMessage.Content.ReadAsAsync<OperatorPosListResponse>().Result;
                    if (operatorPosResponse.ErrorCode == 0 && string.IsNullOrEmpty(operatorPosResponse.Message))
                    {
                        PosModel.PosListData data = new PosModel.PosListData();
                        int i = 0;
                        foreach (var c in operatorPosResponse.PosLists)
                        {
                            i++;
                            #region Формируем выпадающий список для списка ТТ
                            var detailList = c.Poses.Aggregate(string.Empty, (current, pos) => current + (@"<tr>
                                        <td colspan='2' style='color:#000;'>" + pos.City + @"</td>
                                        <td colspan='2' style='color:#000;'>" + pos.Address + @"</td>
                                      </tr>"));
                            #endregion
                            Implementation.Data.OperatorPosList g = new Implementation.Data.OperatorPosList
                            {
                                Id = c.Id,
                                Caption = c.Caption,
                                Text = c.Poses.Count().ToString(),
                                Poses = c.Poses,

LCManagerClient/LCManager.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LC-Manager</title>
    
    <!-- #region Подключаем стили календаря -->
    @Styles.Render("~/Style/jquery-uitheme")
    @Styles.Render("~/Style/jqueryformstyler")
    <!-- #endregion -->
    @RenderSection("Styles", required: false)
    <link rel="stylesheet" href="~/Content/animate.css">
    <link rel="stylesheet" href="~/Content/style.css">
</head>
<body>
    <div class="main-flex">
        <aside class="aside">
            <div class="aside__fix">
                <div class="aside__head">«@(ViewBag.OperatorName)»</div>
                @*<div class="aside__head">«@(LC_Manager.Models.UserData.OperatorName)»</div>*@
                <nav class="aside__links">
                    <ul class="aside__links-ul aside__links-ul_first">
                        @if (ViewBag.RoleName.Contains("Analytics"))
                        {
                            <li class="@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "index" && ViewContext.RouteData.Values["Controller"].ToString().ToLower() == "home" ? "active" : "")">
                                <a href="@Url.Action("Index", "Home")" class="aside-link">
                                    <i class="icon-nav icon-nav_analytic"></i>
                                    <span>Аналитика</span>
                                </a>
                            </li>
                        }
                        @if (ViewBag.RoleName.Contains("Terminal"))
                        {
                            <li class='@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "terminal" ? "active" : "")'>
                                <a href="@Url.Action("Terminal", "Home")" class="aside-link">
                                    <i class="icon-nav icon-nav_sell"></i>
                                    <span>Терминал</span>
                                </a>
                            </li>
                        }
                        @if (ViewBag.RoleName.Contains("Sales"))
                        {
                            <li class='@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "sales" ? "active" : "")'>
                                <a href="@Url.Action("Sales", "Home")" class="aside-link">
                                    <i class="icon-nav icon-nav_sell"></i>
                                    <span>Продажи</span>
                                </a>
                            </li>
                        }
                        @if (ViewBag.RoleName.Contains("Clients"))
                        {
                            <li class='@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "clients" ? "active" : "")'>
                                <a href="@Url.Action("Clients", "Home")" class="aside-link">
                                    <i class="icon-nav icon-nav_clients"></i>
                                    <span>Клиенты</span>
                                </a>
                            </li>
                        }
                        @if (ViewBag.RoleName.Contains("BonusNoCheque"))
                        {
                            <li class="@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "index" && ViewContext.RouteData.Values["Controller"].ToString().ToLower() == "bonus" ? "active" : "")">
                                <a href="@Url.Action("Index", "Bonus")" class="aside-link">
                                    <i class="icon-nav icon-nav_action"></i>
                                    <span>Бонусы</span>
                                </a>
                            </li>
                        }
                        @if (ViewBag.RoleName.Contains("Mailing"))
                        {
                            <li class="@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "distributions" ? "active" : "")">
                                <a href="@Url.Action("Distributions", "Home")" class="aside-link">
                                    <i class="icon-nav icon-nav_action"></i>
                                    <span>Рассылки</span>
                                </a>
                            </li>
                        }
                        @if (ViewBag.RoleName.Contains("Campaign"))
                        {
                            <li class="@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "campaigns" ? "active" : "")">
                                <a href="@Url.Action("Campaigns", "Home")" class="aside-link">
                                    <i class="icon-nav icon-nav_action"></i>
                                    <span>Акции</span>
                                </a>
                            </li>
                        }
                        @if (ViewBag.RoleName.Contains("Shops"))
                        {
                            <li class="@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "index" && ViewContext.RouteData.Values["Controller"].ToString().ToLower() == "pos" ? "active" : "")">
                                <a href="@Url.Action("Index", "Pos")" class="aside-link">
                                    <i class="icon-nav icon-nav_setting"></i>
                                    <span>Точки продаж</span>
                                </a>
                            </li>
                        }
                    </ul>
                    @if (ViewBag.RoleName.Contains("Total"))
                    {
                        <ul class="aside__links-ul aside__links-ul_two">
                            <li class="@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "index" && ViewContext.RouteData.Values["Controller"].ToString().ToLower() == "bookkeeping" ? "active" : "")">
                                <a href="@Url.Action("Index", "Bookkeeping")" class="aside-link">
                                    <i class="icon-nav icon-nav_bux"></i>
                                    <span>Сверка</span>
                                </a>
                            </li>
                        </ul>
                    }
                    @if (ViewBag.RoleName.Contains("Goods"))
                    {
                        <ul class="aside__links-ul aside__links-ul_three">
                            <li class="@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "index" && ViewContext.RouteData.Values["Controller"].ToString().ToLower() == "good" ? "active" : "")">
                                <a href="@Url.Action("Index", "Good")" class="aside-link">
                                    <i class="icon-nav icon-nav_faq"></i>
                                    <span>Товары</span>
                                </a>
                            </li>
                        </ul>
                    }

                    @if (ViewBag.RoleName.Contains("Faq"))
                    {
                        <ul class="aside__links-ul aside__links-ul_three">
                            <li class="@(ViewContext.RouteData.Values["Action"].ToString().ToLower() == "faq" ? "active" : "")">
                                <a href="@Url.Action("FAQ", "Home")" class="aside-link">
                                    <i class="icon-nav icon-nav_faq"></i>
                                    <span>FAQ</span>
                                </a>
                            </li>
                        </ul>
                    }
                </nav>
            </div>
        </aside>
        <div class="content">
            <header class="content__header">
                <a href="" class="btn-hide-aside"></a>
                <ul class="content__header-nav">
                    @RenderSection("ContentHeaderNav", false)
                </ul>
                <a href="@Url.Action("Logoff", "Account")" class="content__header-logout">
                    <i></i>
                    <span>Выйти</span>
                </a>
                <div class="content__search">
                    <div class="content__search__left">
                        <div class="search-form">
                            <button class="search-form__submit"></button>
                            <input type="text" class="search-form__input" placeholder="Поиск клиента по номеру телефона">
                            <button class="search-form__cancel"></button>
                        </div>
                    </div>
                    <div class="content__search__right">
                        <div class="search-form">
                            <button class="search-form__submit"></button>
                            <input type="text" class="search-form__input" placeholder="Поиск покупки по номеру чека">
                            <button class="search-form__cancel"></button>
                        </div>
                    </div>
                </div>
                @RenderSection("ContentHeader", false)
            </header>
            @RenderBody()
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/plugins")
    @Scripts.Render("~/bundles/main")

    <!-- #region Подключаем скрипты календаря -->
    @Scripts.Render("~/Scripts/jqueryformstyler")
    @Scripts.Render("~/Scripts/jqueryui")
    @Scripts.Render("~/Scripts/datepicker")
    <!-- #endregion -->



    @Html.Partial("~/Views/Partial/Layout.cshtml")
    @RenderSection("Scripts", required: false)
    @RenderSection("Partial", false)
    <!-- BEGIN JIVOSITE CODE {literal} -->
    <script type='text/javascript'>
        (function () {
            var widget_id = '3uBzf42ZkQ'; var d = document; var w = window; function l() {
                var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/' + widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);
            } if (d.readyState == 'complete') { l(); } else { if (w.attachEvent) { w.attachEvent('onload', l); } else { w.addEventListener('load', l, false); } }
        })();</script>
    <!-- {/literal} END JIVOSITE CODE -->
</body>
</html>