LCManagerClient/LCManager.Site/Controllers/BonusController.cs
using LC_Manager.Models;
using System;
using System.Net.Http;
using System.Web.Mvc;
using System.Globalization;
using LCManager.Infrastructure.Request;
using LCManager.Infrastructure.Response;
using LCManager.JWT;
using Newtonsoft.Json;
using Bonus = LCManager.Infrastructure.Data.Bonus;
using ReportResponse = LCManager.Infrastructure.Response.ReportResponse;

namespace LC_Manager.Controllers
{
    public class BonusController : Controller
    {
        /// <summary>
        /// Открывает представление Бонусы не за покупки
        /// </summary>
        /// <returns></returns>
        [AuthorizeJwt(Roles = "BonusNoCheque")]
        public ActionResult Index()
        {
            try
            {
                ViewBag.OperatorName = Convert.ToString(HttpContext.Request.Cookies["operatorName"].Value);
                ViewBag.RoleName = LC_Manager.Implementation.JwtProps.GetRole();
            }
            catch { }
            return View();
        }

        /// <summary>
        /// Получает список бонусов не за покупки (с пагинацией)
        /// </summary>
        /// <param name="param"></param>
        /// <returns></returns>
        [AuthorizeJwt(Roles = "BonusNoChequeList"), HttpPost]
        public string GetBonuses(JQueryDataTableParamModel param)
        {
            BonusesNotForPurchasesResponse response = new BonusesNotForPurchasesResponse();
            try
            {
                BonusesNotForPurchasesRequest request = new BonusesNotForPurchasesRequest
                {
                    Operator = Implementation.JwtProps.GetOperator(),
                    Date = Request["columns[1][search][value]"],
                    DateStart = Request["date_from"],
                    DateEnd = Request["date_to"],
                    Phone = Request["columns[3][search][value]"],
                    Page = Convert.ToInt64(param.start),
                    PageSize = Convert.ToInt64(param.length)
                };

                if (!string.IsNullOrEmpty(Request["columns[2][search][value]"]))
                {
                    request.Name = Request["columns[2][search][value]"];
                }
                if (!string.IsNullOrEmpty(Request["columns[5][search][value]"]))
                {
                    var values = Request["columns[5][search][value]"].Split('-');
                    try { request.AddedMore = values[0]; } catch { };
                    try { request.AddedLess = values[1]; } catch { };
                }
                if (!string.IsNullOrEmpty(Request["columns[6][search][value]"]))
                {
                    var values = Request["columns[6][search][value]"].Split('-');
                    try { request.RedeemedMore = values[0]; } catch { };
                    try { request.RedeemedLess = values[1]; } catch { };
                }
                if (!string.IsNullOrEmpty(Request["columns[7][search][value]"]))
                {
                    var values = Request["columns[7][search][value]"].Split('-');
                    try { request.BurnMore = values[0]; } catch { };
                    try { request.BurnLess = values[1]; } catch { };
                }
                try { request.Page++; } catch { }
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/client/BonusesNotForPurchases", request).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    try { response = responseMessage.Content.ReadAsAsync<BonusesNotForPurchasesResponse>().Result; } catch { }
                    if (response.ErrorCode == 0)
                    {
                        Bonuses bonuses = new Bonuses();
                        foreach (Bonus c in response.Bonuses)
                        {
                            BonusesViewModel bonus = new BonusesViewModel
                            {
                                date = "<p>" + c.BonusDate.ToString("dd.MM.yyyy") + "</p> <p>" +
                                       c.BonusDate.ToString("HH:mm") + "</p>",
                                type = c.BonusSource,
                                added = c.BonusAdded.ToString(CultureInfo.InvariantCulture),
                                redeemed = c.BonusRedeemed.ToString(CultureInfo.InvariantCulture),
                                fireed = c.BonusBurn.ToString(CultureInfo.InvariantCulture),
                                card = c.BonusCard.ToString(CultureInfo.CurrentCulture),
                                phone = c.Phone,
                                reason = "Механика ПЛ",
                                lorem = ""
                            };
                            bonuses.data.Add(bonus);
                        }
                        bonuses.draw = param.draw;
                        bonuses.recordsTotal = response.RecordTotal;
                        bonuses.recordsFiltered = response.RecordFilterd;
                        var data = JsonConvert.SerializeObject(bonuses);
                        return data;
                    }
                    return responseMessage.ReasonPhrase;
                }
                response.ErrorCode = 10;
                response.Message = "Ошибка получения данных";
            }
            catch (Exception ex)
            {
                response.ErrorCode = 2;
                response.Message = ex.Message;
            }
            return JsonConvert.SerializeObject(response);
        }

        /// <summary>
        /// Отчет по бонусам не за покупки
        /// </summary>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="date"></param>
        /// <param name="shop"></param>
        /// <param name="phone"></param>
        /// <param name="operation"></param>
        /// <param name="cheque"></param>
        /// <param name="sum"></param>
        /// <param name="charge"></param>
        /// <param name="redeem"></param>
        /// <returns></returns>
        [AuthorizeJwt]
        [HttpPost]
        public FileResult BonusNoChequeReport(
            string bonus_from,
            string bonus_to,
            string bonus_date,
            string bonus_type,
            string bonus_added,
            string bonus_redeemed,
            string bonus_burned,
            string bonus_phone)
        {
            try
            {
                BonusesNotForPurchasesRequest request = new BonusesNotForPurchasesRequest
                {
                    Operator = Implementation.JwtProps.GetOperator(),
                    Date = bonus_date,
                    DateStart = bonus_from,
                    DateEnd = bonus_to,
                    Phone = bonus_phone,
                    Page = -1,
                    PageSize = -1
                };

                if (!string.IsNullOrEmpty(bonus_type))
                {
                    request.Name = bonus_type.Substring(1, bonus_type.Length - 2);
                }
                if (!string.IsNullOrEmpty(bonus_added))
                {
                    var values = bonus_added.Split('-');
                    try { request.AddedMore = values[0]; } catch { };
                    try { request.AddedLess = values[1]; } catch { };
                }
                if (!string.IsNullOrEmpty(bonus_redeemed))
                {
                    var values = bonus_redeemed.Split('-');
                    try { request.RedeemedMore = values[0]; } catch { };
                    try { request.RedeemedLess = values[1]; } catch { };
                }
                if (!string.IsNullOrEmpty(bonus_burned))
                {
                    var values = bonus_burned.Split('-');
                    try { request.BurnMore = values[0]; } catch { };
                    try { request.BurnLess = values[1]; } catch { };
                }
                ReportResponse response = new ReportResponse();
                HttpResponseMessage responseMessage = HttpClientService.PostAsync("api/reports/BonusesNoChequeReport", request).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    response = responseMessage.Content.ReadAsAsync<ReportResponse>().Result;
                    if (response.ErrorCode != 0 || !string.IsNullOrEmpty(response.Message)) return null;
                    var reportName = "Отчёт по бонусам не за покупки";
                    if (!string.IsNullOrEmpty(bonus_from)) reportName = reportName + " с " + bonus_from;
                    if (!string.IsNullOrEmpty(bonus_to)) reportName = reportName + " по " + bonus_to;
                    reportName = reportName + ".xlsx";
                    return File(response.Report, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", reportName);
                }
                return null;
            }
            catch { return null; }
        }
    }
}

LCManagerClient/LCManager.Site/Views/Bonus/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    #clientsTable_length label {
        display: flex;
    }

    .table-length span {
        color: #fff !important;
    }

    .table-length div {
        cursor: pointer !important;
        position: relative !important;
        text-align: left !important;
        -webkit-transition: all 0.2s ease-in-out !important;
        transition: all 0.2s ease-in-out !important;
        -webkit-user-select: none !important;
        -moz-user-select: none !important;
        -ms-user-select: none !important;
        user-select: none !important;
        white-space: nowrap !important;
        display: inline-block !important;
        vertical-align: middle !important;
        background-color: #58AEDC !important;
        width: 150px !important;
        border: none !important;
        color: #fff !important;
        -webkit-border-radius: 6px !important;
        border-radius: 6px !important;
        padding: 0px 5px 0px 15px !important;
        height: 36px !important;
        line-height: 36px !important;
        font-weight: 400 !important;
        font-family: 'a_FuturicaMedium' !important;
        font-size: 16rem !important;
        -webkit-appearance: none !important;
        -moz-appearance: none !important;
        appearance: none !important;
        -webkit-box-sizing: border-box !important;
        box-sizing: border-box !important;
        outline: none !important;
        margin: auto 0 !important;
    }

    .table-length .nice-select {
        width: 65px !important;
        margin-top: 6px !important;
        float: left !important;
    }
</style>



@section ContentHeaderNav
{
    @if (ViewBag.RoleName.Contains("OperatorBonusAdd"))
    {
        <li><a href="" id="HandBonusAdd"><img src="../img/plus.png" alt="addbonus"><span>Начислить бонусы</span></a></li>
    }
    @if (ViewBag.RoleName.Contains("OperatorBonusRedeem"))
    {
        <li><a href="" id="HandBonusRedeem"><img src="../img/minus.png" alt="message"><span>Списать бонусы</span></a></li>
    }
    @if (!ViewBag.RoleName.Contains("OperatorBonusAdd") && !ViewBag.RoleName.Contains("OperatorBonusRedeem"))
    {
        <li><a style="visibility:hidden;">.</a></li>
    }
    @if (ViewBag.RoleName.Contains("ActivateCard"))
    {
        <li><a href="#" id="activateCard"><img src="../img/plus.png" alt="addclient"><span>Активировать карту</span></a></li>
    }
}

@section ContentHeader
{
    @*<div class="client_nav">
        @if (ViewBag.RoleName.Contains("BonusNoChequeList"))
        {
            <div><div>?<p>В данном разделе можно фильтровать и просматривать информацию по бонусам не относящимся к покупкам.</p></div><a href="#allbonuses" class="this-p">Все бонусы</a></div>
        }
        <div style="float: right"><p>Всего бонусов: <span id="bonusesCount"></span></p></div>
    </div>*@
    
<div class="filters">
    <p>Показать бонусы с </p>
    <input type="text" name=" date-item" class=" zbz-input-clearable datepicker" id="dateFrom">
    <p> по </p>
    <input type="text" name="date-item " class=" zbz-input-clearable datepicker" id="dateTo">
    <div class="table__clear_meu">
        <p class="clear-date" id="claerDateBonuses">Сбросить даты</p>
        <p id="claerAllFilters">Сбросить все фильтры</p>
    </div>
</div>
}

<section class="table-min-width">
    <div class="form-terminal__tabs-content">
        @if (ViewBag.RoleName.Contains("BonusNoCheque"))
        {
            <div id="allbonuses" class="@(ViewBag.RoleName.Contains("BonusNoCheque") ? "active" : "")" style="margin-bottom: 100px">
                <div class="datatables-div">
                    <table id="clients-bonuses" class="display selling hl-table w100" cellspacing="0">
                        <thead>
                        <tr>
                            <th></th>
                            <th>
                                <p>Дата</p></th>
                            <th>
                                <p>Тип бонуса</p></th>
                            <th>
                                <p>Телефон</p></th>
                            <th>
                                <p>Основание</p></th>
                            <th>
                                <p>Начислено</p></th>
                            <th>
                                <p>Списано</p></th>
                            <th>
                                <p>Сгорело</p></th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                    <div class="page-navigation">
                        <div class="table__download_meu">
                            <div>?
                                <p style="font-family: 'a_Futurica'; text-align: left;">Скачать отчёт по движению бонусов не за покупки, за период, с фильтрацией.</p>
                            </div>
                            @using (Html.BeginForm("BonusNoChequeReport", "Bonus", FormMethod.Post, new {id = "export-bonuses-no-cheque-to-file-form", style = "display: flex"}))
                            {
                                @Html.Hidden("bonus_from", string.Empty)
                                @Html.Hidden("bonus_to", string.Empty)
                                @Html.Hidden("bonus_date", string.Empty)
                                @Html.Hidden("bonus_type", string.Empty)
                                @Html.Hidden("bonus_added", string.Empty)
                                @Html.Hidden("bonus_redeemed", string.Empty)
                                @Html.Hidden("bonus_burned", string.Empty)
                                @Html.Hidden("bonus_phone", string.Empty)
                                <p>Скачать отчет: </p>
                                <a href="#" id="export-bonuses-no-cheque-to-file">XLSX</a>
                            }

                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

@section Scripts {
    <script type="text/javascript">
        var tableBonuses;
        var serchingRowBonuses = false;

        $("#dateFrom, #dateTo").on('change input', function(){
            tableBonuses.draw();
        });

        $("#claerDateBonuses").on("click", function(){
            clearDateBonuses();
        });

        $("#export-bonuses-no-cheque-to-file").on("click", function(e) {
            e.preventDefault();
            $("#bonus_from").val($("#dateFrom").val());
            $("#bonus_to").val($("#dateTo").val());
            $("#bonus_date").val(tableBonuses.column(1).search());
            $("#bonus_type").val(tableBonuses.column(2).search());
            $("#bonus_added").val(tableBonuses.column(5).search());
            $("#bonus_redeemed").val(tableBonuses.column(6).search());
            $("#bonus_burned").val(tableBonuses.column(7).search());
            $("#bonus_phone").val(tableBonuses.column(3).search());
            $("#export-bonuses-no-cheque-to-file-form").submit();
        });

        function clearDateBonuses(){
            $("#dateFrom").val("").removeClass("zbz-input-clearable__x");
            $("#dateTo").val("").removeClass("zbz-input-clearable__x");
            tableBonuses.draw();
        }

        $(function () {
            tableBonuses = $('#clients-bonuses').DataTable({
                "searchDelay": 1000,
                "serverSide": true,
                "processing": true,
                "language": {
                    processing: '<div class="wrapper-for-loading-datatable"><img src="/img/loading-element-1.svg" alt="Alternate Text" /><span class="sr-only">Загрузка...</span></div>'
                },
                //"lengthChange": false,
                "info": false,
                "ajax":
                {
                    method: "POST",
                    url: "../Bonus/GetBonuses",
                    data: function (params) {
                        params.date_from = $("#dateFrom").val();
                        params.date_to = $("#dateTo").val();
                    }
                },
                "columns": [
                    {
                        "className": 'details-control',
                        "orderable": false,
                        "data": null,
                        "defaultContent": '<img src="../img/tableiconopen.png"><br/><i class="details-arrow"></i>'
                        //"defaultContent": '<i class="details-arrow"></i>'
                    },
                    { "data": "date" },
                    { "data": "type" },
                    { "data": "phone" },
                    { "data": "reason" },
                    { "data": "added" },
                    { "data": "redeemed" },
                    { "data": "fireed" },
                ],
                "ordering": false,
                initComplete: function () {
                    $("#clients-bonuses_length").appendTo($(".filters"));
                    $("#clients-bonuses_length").css('display', 'flex');
                    this.api().columns([1]).every(function () {
                        addInputFilterWoAuto(this, ' datepicker');
                    });
                    this.api().columns([3]).every(function () {
                        addInputFilter(this);
                    });
                    this.api().columns([2]).every(function () {
                        var column = this;
                        var select = $('<select><option value=""></option></select>')
                            .appendTo($(column.header()))
                            .bind('keyup change',
                                function () {
                                    column.search($(this).val());
                                    tableBonuses.draw();
                                });

                        select.append('<option value="Operator Bonus">Operator Bonus</option>');
                        select.append('<option value="Birthday Bonus">Birthday Bonus</option>');
                        select.append('<option value="Friend Bonus">Friend Bonus</option>');
                        select.append('<option value="Promo Bonus">Promo Bonus</option>');
                        select.append('<option value="Friend Cashback">Friend Cashback</option>');
                        select.append('<option value="Welcome Bonus">Welcome Bonus</option>');
                    });
                    this.api().columns([4]).every(function () {
                        addSelectFilter(this);
                    });
                    this.api().columns([5, 6, 7]).every(function () {
                        var column = this;
                        var select = $('<select><option value=""></option></select>')
                            .appendTo($(column.header()))
                            .bind('keyup change', function () {
                                column.search($(this).val());
                                tableBonuses.draw();
                            });
                        select.append('<option value="1-100">1-100</option>');
                        select.append('<option value="100-500">100-500</option>');
                        select.append('<option value="500-1000">500-1000</option>');
                        select.append('<option value="1000-9000">1000-9000</option>');
                    });
                    niceSelect();
                    $(".nice-select ul.list li.focus").removeClass('focus');
                }
            });

            tableBonuses.on("draw", function () {
                if (serchingRowBonuses) {
                    if (!$("#clients-bonuses tbody tr:first-child td:first-child").hasClass('dataTables_empty')) {
                        $("#clients-bonuses tbody tr:first-child td:first-child").trigger('click');
                        serchingRowBonuses = false;
                    }
                }
            });

            $("#clients-bonuses tbody").on('click', 'tr.odd td, tr.even td', function () {
                var tr = $(this).closest('tr');
                var row = tableBonuses.row(tr);
                showHideRow(tr, row, format);
            });

        });
    </script>
}